allowBuilds:
  '@parcel/watcher': true
  pandora-common: true
  pandora-common@git+https://github.com/Project-Pandora-Game/pandora.git: true
  sharp: true
  unrs-resolver: true

allowUnusedPatches: false
injectWorkspacePackages: false
minimumReleaseAge: 2880
minimumReleaseAgeExclude:
  - pandora-common
nodeOptions: --no-warnings=ExperimentalWarning --experimental-vm-modules
autoInstallPeers: false
strictPeerDependencies: true
updateNotifier: false
verifyDepsBeforeRun: install
trustLockfile: true
