name: CI

on:
  # Triggers the workflow on push but only for the master branch
  push:
    branches: [ master ]
  # Triggers the workflow on any pull request
  pull_request:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
        with:
          lfs: false
        env:
          NO_GIT_LFS: '1'
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: yarn install --frozen-lockfile
      - run: yarn build

  lint:
    name: Lint
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
        with:
          lfs: false
        env:
          NO_GIT_LFS: '1'
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: yarn install --frozen-lockfile
      - run: yarn lint

  test:
    name: Test
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
        with:
          lfs: false
        env:
          NO_GIT_LFS: '1'
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: yarn install --frozen-lockfile
      - run: yarn type-check:test
      - run: yarn test
