name: Submodule Check

on:
  # Triggers the workflow on push but only for the master branch
  push:
    branches:
      - master
      - 'renovate/**'
  # Triggers the workflow on any pull request
  pull_request:

jobs:
  submodule_check:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Checkout Submodules
        run: git submodule update --init --force

      - name: Check Pandora Submodule
        run: |
          # Get the current hash for pandora
          current_hash=$(git submodule status pandora | awk '{print $1}')

          # Get the hash for my_submodule from origin/master
          git fetch origin master
          master_hash=$(git ls-tree origin/master pandora | awk '{print $3}')

          if [ "$current_hash" == "$master_hash" ]; then
            # skip the rest of the checks
            exit 0
          fi

          # Check if current is based on master
          cd pandora
          git fetch origin master
          if git merge-base --is-ancestor $current_hash $master_hash; then
            echo "Error: Pandora submodule is not up to date with origin/master" >&2
            exit 1
          fi

          # Get the HEAD for the submodule repo on its origin/master
          origin_master_hash=$(git rev-parse --verify origin/master)

          # Check if this contains the current pandora hash
          if ! git merge-base --is-ancestor $current_hash $origin_master_hash; then
            echo "Error: Pandora submodule is not part of origin/master" >&2
            exit 1
          fi
